### ISSUE TITLE
Refactor CardGenerator.cs

### ISSUE THREAD

**Issue by revenkogrisha** [revenkogrisha/Memory2D#2]
Remove `_card` and maybe `_grid` fields. Also it might be better to move two private methods into new class, for instance, `CardSetter.cs` or something like that. Maybe `CardGenerator.cs` could spawn cards on the scene, and then `CardSetter.cs` take array of cards and set them up.

**Comment by pkplonker** [comment]
Happy to help, but there isn't enough of the project on the repo to see what is happening. From a single script, cardgenerator.cs looks good.

**Comment by revenkogrisha** [comment]
Hey. Seemingly I planned to remove `_card` and maybe `_grid` fields. Also it might be better to move two private methods into new class, for instance, `CardSetter.cs` or something like that. Maybe `CardGenerator.cs` could spawn cards on the scene, and then `CardSetter.cs` take array of cards and set them up. Ofc it's unnessesary for such a simple project, I'm just practicing :)

**Comment by pkplonker** [comment]
Are you able to add the required project files to allow me to build and test a solution ? :) Thanks

**Comment by revenkogrisha** [comment]
> Are you able to add the required project files to allow me to build and test a solution ? :) Thanks

Added archive with entire project into Releases. (Cannot just push bcs have large files)
